### ISSUE TITLE
ONNX optimizers are broken for PyTorch 1.3 and so on

### ISSUE THREAD

**Issue by Royzon** [daquexian/onnx-simplifier#25] opened 2019-10-23 06:13 UTC
I got this "IndexError: _Map_base::at" when simliplify my onnx model. 
python3 -m onnxsim model.onnx model_sim.onnx
Simplifying...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/.local/lib/python3.5/site-packages/onnxsim/__main__.py", line 24, in <module>
    main()
  File "/.local/lib/python3.5/site-packages/onnxsim/__main__.py", line 17, in main
    model_opt = onnxsim.simplify(args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization)
  File "/.local/lib/python3.5/site-packages/onnxsim/onnx_simplifier.py", line 197, in simplify
    model_opt = optimize(model_opt)
  File "/.local/lib/python3.5/site-packages/onnxsim/onnx_simplifier.py", line 157, in optimize
    fixed_point=True)
  File "/.local/lib/python3.5/site-packages/onnx/optimizer.py", line 53, in optimize
    optimized_model_str = C.optimize_fixedpoint(model_str, passes)
IndexError: _Map_base::at

-----------

From daquexian:

> It is a bug of ONNX and we have to wait for ONNX maintainers to fix it.
> 
> Some workarounds: https://github.com/daquexian/onnx-simplifier/issues/25#issuecomment-547247229

**Comment by daquexian** [comment] 2019-10-23 06:21
thanks for your issue, could you please send your model to daquexian566@gmail.com? thanks!

**Comment by Royzon** [comment] 2019-10-23 06:33
sent already.

**Comment by daquexian** [comment] 2019-10-23 06:36
@Royzon Thanks, I believe it is a bug of ONNX. As a quick workaround, you can replace the `True` in https://github.com/daquexian/onnx-simplifier/blob/master/onnxsim/onnx_simplifier.py#L157 with `False`

**Comment by mengchengxxx** [comment] 2019-10-23 06:49
@daquexian I replaced the true in https://github.com/daquexian/onnx-simplifier/blob/master/onnxsim/onnx_simplifier.py#L157 with False，it is fail like this：

`Simplifying...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cmeng/onnx-simplifier/onnxsim/__main__.py", line 24, in <module>
    main()
  File "/home/cmeng/onnx-simplifier/onnxsim/__main__.py", line 17, in main
    model_opt = onnxsim.simplify(args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization)
  File "/home/cmeng/onnx-simplifier/onnxsim/onnx_simplifier.py", line 197, in simplify
    model_opt = optimize(model_opt)
  File "/home/cmeng/onnx-simplifier/onnxsim/onnx_simplifier.py", line 157, in optimize
    fixed_point=False)
  File "/home/cmeng/.local/lib/python3.6/site-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: _Map_base::at
`

**Comment by daquexian** [comment] 2019-10-23 06:53
@mengchengxxx thanks, I have reproduced it on my side. I'm on vacation these days so I will look into it once I'm back to work

**Comment by nihui** [comment] 2019-10-24 06:54
hi all
I finally resolved this issue

you have to add keep_initializers_as_inputs=True when exporting onnx

```
torch.onnx._export(model, x, "model.onnx", export_params=True, keep_initializers_as_inputs=True)
```

since this commit

https://github.com/pytorch/pytorch/commit/7583519b870e33ee3182f330c1bb8663559697b6

**Comment by muzi2045** [comment] 2019-10-24 10:48
[pfe.onnx.tar.gz](https://github.com/daquexian/onnx-simplifier/files/3767078/pfe.onnx.tar.gz)
this onnx file using onnx-simplifier will try to allocate a lot memory space.

**Comment by daquexian** [comment] 2019-10-24 19:43
Related issue: https://github.com/onnx/onnx/issues/2417

**Comment by daquexian** [comment] 2019-10-29 04:06
It is a bug of ONNX and we have to wait for ONNX maintainers to fix it. 

Some workarounds:

- Downgrade PyTorch to 1.2 or lower and export the ONNX model again, or
- Add keep_initializers_as_inputs=True when exporting onnx as in https://github.com/daquexian/onnx-simplifier/issues/25#issuecomment-545773885

**Comment by daquexian** [comment] 2019-10-31 23:41
Since this bug cannot be fixed in ONNX in the short term, I added initializers into inputs manually in onnx-simplifier so that this bug has been "fixed" in onnx-simplifier now. However, I am still looking forward to the bugfix from onnx maintainers.

**Closed by daquexian** 2019-10-31 23:41 UTC
Labels: external issue
